version: "3.8"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: cuongnm/laravel-docker
    container_name: web
    volumes:
      - ./web:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - mysql
      - nginx
      - redis
  mysql:
    image: mysql:5.7.33
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: employees
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - laravel
networks:
  laravel:
